Feature/response renderers
nmshd/cns-app pull request #100
Opened 2023-10-30 16:49 UTC by Vin-RM

2023-11-03 13:30 UTC, nicole-eb requested changes

2023-11-03 13:30 UTC, nicole-eb commented on packages/renderers/lib/src/renderers/request_item_renderer/response/response_item_renderer.dart
>            'RejectResponseItemDVO' => Column(crossAxisAlignment: CrossAxisAlignment.start, children: requestItemList), //Add Rejected message
Have you tested the RejectResponse? I think there is an issue with displaying the items too many times (you can see it in the  RequestsExample and RejectedCreateAttributeRequestJsonExample )

2023-11-07 07:41 UTC, aince42 commented on packages/renderers/lib/src/renderers/request_item_renderer/widgets/draft_attribute_renderer.dart
> +            description: isRejected == false ? attributeValueMap['value'].toString() : null,
`isRejected != null && !isRejected ? attributeValueMap['value'].toString() : null,`

2023-11-07 07:41 UTC, aince42 commented on packages/renderers/lib/src/renderers/request_item_renderer/widgets/draft_attribute_renderer.dart
> +        description: isRejected == false ? attributeValueMap['value'].toString() : null,
`isRejected != null && !isRejected ? attributeValueMap['value'].toString() : null,`

2023-11-08 10:53 UTC, nicole-eb requested changes

2023-11-08 10:53 UTC, nicole-eb commented on packages/renderers/lib/src/renderers/request_item_renderer/response/response_item_renderer.dart
> +import 'package:renderers/src/renderers/request_item_renderer/request_item_renderer.dart';
use local import

2023-11-08 10:53 UTC, nicole-eb commented on packages/renderers/lib/src/renderers/request_item_renderer/widgets/draft_attribute_renderer.dart
> +            // description: isRejected == false ? attributeValueMap['value'].toString() : null,
remove commented out code

2023-11-08 11:06 UTC, nicole-eb approved these changes

2023-11-14 07:31 UTC, jkoenig134 requested changes

2023-11-14 07:31 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/request_item_renderer.dart
> +  const RequestItemRenderer({super.key, required this.item, this.controller, this.onEdit, this.isRejected = false});
I think this is duplicated information thats already in the RequestItemDVO and in the Request Items.

2023-11-14 07:31 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/request_item_renderer.dart
> +      final CreateAttributeRequestItemDVO dvo => CreateAttributeRequestItemRenderer(controller: controller, item: dvo, isRejected: isRejected!),
If you know isRejected is always defined - why don't you just make it required?
Please not overuse the postfix exclamation mark.

2023-11-14 07:31 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/create_attribute_request_item.dart
> +    return DraftAttributeRenderer(draftAttribute: item.attribute, isRejected: isRejected);
also here, this information (`isRejected`) should already be defined in the CreateAttributeRequestItemDVO

2023-11-14 07:31 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/response/create_attribute_accept_response_item_renderer.dart
> +      description: item.attribute.value.toJson()['value'],
this will explode for complex attributes.

2023-11-14 07:31 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/response/create_attribute_accept_response_item_renderer.dart
> +      description: item.attribute.value.toJson()['value'],
for that - do not work on json if it is avoidable
you are yeeting ALL type safety when running toJson

2023-11-14 07:31 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/response/propose_attribute_accept_response_item_renderer.dart
> +      description: item.attribute.value.toJson()['value'],
see CreateAttributeAcceptResponseItemRenderer

2023-11-14 07:31 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/response/read_attribute_accept_response_item_renderer.dart
> +      description: item.attribute.value.toJson()['value'],
see CreateAttributeAcceptResponseItemRenderer

2023-11-14 07:31 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/response/register_attribute_accept_response_item_renderer.dart
> +class RegisterAttributeAcceptResponseItemRenderer extends StatelessWidget {
what is a RegisterAttribute?

I only know the RegisterAttribute**Listener**RequestItem

2023-11-14 07:31 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/response/register_attribute_accept_response_item_renderer.dart
> +      description: item.listener.name,
I think both must be translatable

2023-11-14 07:31 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/response/response_item_group_renderer.dart
> +      },
make this an arrow fn

2023-11-14 07:31 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/response/response_item_group_renderer.dart
> +  final RequestItemGroupDVO requestItem;
naming

2023-11-14 07:31 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/response/response_item_renderer.dart
>        final ErrorResponseItemDVO dvo => Text(dvo.type),
please render this out properly

2023-11-14 07:31 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/response/response_item_renderer.dart
> +          'RejectResponseItemDVO' => RequestItemRenderer(item: requestItem, isRejected: true),
why is there a switch over the type?

2023-11-14 07:31 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/response/response_item_renderer.dart
> +          'RejectResponseItemDVO' => RequestItemRenderer(item: requestItem, isRejected: true),
I think we should make an RejectResponseItemRenderer for that

2023-11-14 07:31 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/response/share_attribute_accept_response_item_renderer.dart
> +      description: item.attribute.value.toJson()['value'],
see CreateAttributeAcceptResponseItemRenderer

2023-11-14 07:31 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/widgets/draft_attribute_renderer.dart
>    final dynamic draftAttribute;
dynamic?!

2023-11-14 07:31 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/widgets/draft_attribute_renderer.dart
> +            description: isRejected != null && isRejected == true ? null : attributeValueMap['value'].toString(),
unsafe access to value

2023-11-14 07:31 UTC, jkoenig134 commented on packages/renderers/lib/src/request_renderer.dart
> +        return ResponseItemRenderer(item: item, requestItem: request.items[index]);
naming. should be `requestItem` as a field in ResponseItemRenderer

2023-11-21 10:50 UTC, Vin-RM commented on packages/renderers/lib/src/renderers/request_item_renderer/create_attribute_request_item.dart
> +    return DraftAttributeRenderer(draftAttribute: item.attribute, isRejected: isRejected);
Not applicable.

2023-11-22 15:21 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/widgets/draft_attribute_renderer.dart
>      if (attributeValueMap.length == 2) {
maybe also make sure that the `attributeValueMap` contains the key `value`, then you can re-add the `!`

2023-11-24 09:56 UTC, jkoenig134 approved these changes

2023-11-24 10:24 UTC, merged