Feature/add decidable identity attribute renderer without results
nmshd/cns-app pull request #103
Opened 2023-11-03 13:49 UTC by aince42

2023-11-08 13:54 UTC, nicole-eb requested changes

2023-11-08 13:54 UTC, nicole-eb commented on packages/renderers/example/assets/i18n/de.json
> +            "BR": "Brazil",
The countries are in english in the de.json

2023-11-08 13:54 UTC, nicole-eb commented on packages/renderers/example/assets/i18n/de.json
> +            },
do we need houseNo and houseNumber ? If so, then  translation for houseNumber is missing in the en.json

2023-11-08 13:54 UTC, nicole-eb commented on packages/renderers/lib/src/renderers/widgets/complex_attribute_list_tile.dart
> +            SizedBox(width: 50, child: trailing ?? IconButton(onPressed: onPressed, icon: const Icon(Icons.chevron_right))),
i think `  if (trailing != null)` needs to stay because ComplexAttributeListTile is also used by non decidable

2023-11-08 13:54 UTC, nicole-eb commented on packages/renderers/lib/src/renderers/widgets/custom_list_tile.dart
> +        const Divider(height: 0),
i think we don't  need a divider - maybe ask Claus / Franz

2023-11-10 14:42 UTC, nicole-eb approved these changes

2023-11-15 11:53 UTC, jkoenig134 requested changes

2023-11-15 11:53 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/renderers/complex.dart
> +    final fieldName = widget.shouldTranslate ? 'i18n://attributes.values.${widget.fieldName}._title' : widget.fieldName;
that should come from outside

2023-11-15 11:53 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/renderers/complex.dart
> +                const SizedBox(height: 16),
spacing should be done outside

2023-11-15 11:53 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/renderers/complex.dart
> +            return Column(
why is the list tile removed?

2023-11-15 11:53 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/renderers/number.dart
> +    if (initialNumberValue != null) valueHintsDefaultValue = ValueHintsDefaultValueNum(initialNumberValue);
see bool

2023-11-15 11:53 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/renderers/string.dart
> +            : this.fieldName;
we need to talk about that `shouldTranslate`

2023-11-16 15:19 UTC, nicole-eb requested changes

2023-11-16 15:19 UTC, nicole-eb commented on packages/renderers/example/assets/i18n/en.json
>        }
error translations are missing: 

  "errors": {
    "value_renderer": {
      "emptyField": "This field cannot be empty",
      "maxValue": "Value must be less than or equal to {value}",
      "minValue": "Value must be greater than or equal to {value}",
      "invalidInput": "Invalid Input",
      "invalidFormat": "Invalid Format",
      "noDateSelected" : "No date selected"
    }
  }

2023-11-16 15:19 UTC, nicole-eb commented on packages/renderers/example/assets/i18n/de.json
>        }
error translations are missing.

"errors": {
"value_renderer": {
"emptyField": "Dieses Feld kann nicht leer sein",
"maxValue": "Der Wert muss kleiner oder gleich {value} sein",
"minValue": "Der Wert muss größer oder gleich {value} sein",
"invalidInput": "Ungültige Eingabe",
"invalidFormat": "Ungültiges Format",
"noDateSelected" : "Kein Datum ausgewählt"
}
}

2023-11-20 12:17 UTC, aince42 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/widgets/processed_query_renderer.dart
> +        const SizedBox(height: 16),
It's the space between textfields, if there are more then one attribute in one request.

2023-11-20 12:18 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/widgets/processed_query_renderer.dart
> +        const SizedBox(height: 16),
such spaces should be made outside.

2023-11-20 12:22 UTC, aince42 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/widgets/processed_query_renderer.dart
> +        const SizedBox(height: 16),
How we can do it from outside?
We just call the RequestRenderer from outside, and if there are more then one attribute in the request, then the textfields don't have a space between.

2023-11-20 12:23 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/widgets/processed_query_renderer.dart
> +        const SizedBox(height: 16),
you must add these spacers in ListView.separated or so

2023-11-20 12:50 UTC, aince42 commented on packages/value_renderer/lib/src/widgets/renderers/complex.dart
> +            return Column(
Because the ListTile creates unnecessary space on the right and left.

2023-11-20 12:54 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/renderers/complex.dart
> +            return Column(
why don't make it customizable?

2023-11-22 09:08 UTC, jkoenig134 requested changes

2023-11-22 09:08 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/widgets/value_renderer_list_tile.dart
>      );
usage of trailing removed -> widget can still be passed

2023-11-22 09:08 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/renderers/complex.dart
> +    if (widget.initialValue is BirthDateAttributeValue || widget.fieldName == 'BirthDate') {
go back to old code

2023-11-22 09:08 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/widgets/identity_attribute_value_renderer.dart
> +        trailing: IconButton(onPressed: onEdit != null ? () => onEdit!() : null, icon: const Icon(Icons.chevron_right)),
```suggestion
        trailing: IconButton(onPressed: onEdit, icon: const Icon(Icons.chevron_right)),
```

2023-11-22 09:08 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/widgets/identity_attribute_value_renderer.dart
> +      trailing: IconButton(onPressed: onEdit != null ? () => onEdit!() : null, icon: const Icon(Icons.chevron_right)),
```suggestion
      trailing: IconButton(onPressed: onEdit, icon: const Icon(Icons.chevron_right)),
```

2023-11-22 09:08 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/widgets/processed_query_renderer.dart
> +              'StreetAddress' => 'i18n://attributes.values.${query.valueType}._title',
combine these cases

2023-11-22 09:08 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/widgets/processed_query_renderer.dart
> +        ? ValueRendererListTile(
use early return instead of ternary

2023-11-22 09:08 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/widgets/processed_query_renderer.dart
> +  final VoidCallback? onEdit;
onEdit isn't used in this widget

2023-11-22 12:16 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/widgets/processed_query_renderer.dart
> +          _ => 'i18n://dvo.attribute.name.${query.valueType[0].toUpperCase() + query.valueType.substring(1)}',
isn't the `._title` missing here?

2023-11-22 12:19 UTC, aince42 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/widgets/processed_query_renderer.dart
> +          _ => 'i18n://dvo.attribute.name.${query.valueType[0].toUpperCase() + query.valueType.substring(1)}',
No, the simple identity attributes don't have a ._title in the translation files

2023-11-22 12:20 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/widgets/processed_query_renderer.dart
> +          _ => 'i18n://dvo.attribute.name.${query.valueType[0].toUpperCase() + query.valueType.substring(1)}',
so only the complex ones?

2023-11-22 12:21 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/widgets/processed_query_renderer.dart
> +          _ => 'i18n://dvo.attribute.name.${query.valueType[0].toUpperCase() + query.valueType.substring(1)}',
additionally - why do we need to make the first letter uppercase? value types should already be uppercase.

2023-11-22 12:26 UTC, aince42 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/widgets/processed_query_renderer.dart
> +          _ => 'i18n://dvo.attribute.name.${query.valueType[0].toUpperCase() + query.valueType.substring(1)}',
You are right, there was a case when we did the translation directly in the ValueRenderer, but here it is unnecessary.
I'll change it

2023-11-22 12:38 UTC, jkoenig134 commented on packages/renderers/example/assets/i18n/de.json
> +            },
@aince42 explain please

2023-11-22 12:41 UTC, jkoenig134 commented on packages/renderers/example/assets/i18n/en.json
>        }
@aince42 ?

2023-11-22 12:41 UTC, jkoenig134 commented on packages/renderers/example/assets/i18n/de.json
>        }
@aince42 ?

2023-11-22 12:42 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/widgets/value_renderer_list_tile.dart
>      );
@aince42 ?

2023-11-22 13:26 UTC, jkoenig134 approved these changes

2023-11-23 07:36 UTC, aince42 commented on packages/renderers/example/assets/i18n/de.json
> +            },
We need the `houseNo` to translate the key of `StreetAddress.houseNo`.

2023-11-23 07:37 UTC, aince42 commented on packages/renderers/example/assets/i18n/de.json
>        }
Is already implemented

2023-11-23 07:37 UTC, aince42 commented on packages/renderers/example/assets/i18n/de.json
>        }
Is already implemented

2023-11-23 07:55 UTC, jkoenig134 approved these changes

2023-11-23 07:56 UTC, merged