Feature/share and authentication decidables
nmshd/cns-app pull request #105
Opened 2023-11-13 13:40 UTC by nicole-eb

2023-11-13 16:45 UTC, Vin-RM approved these changes

2023-11-14 15:29 UTC, jkoenig134 commented
tests failing, I'll start with the review when this is fixed.

2023-11-15 10:36 UTC, jkoenig134 requested changes

2023-11-15 10:36 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/decidable_authentication_request_item_renderer.dart
> +    );
I don't get this. You only render the name? WTB the authentication itself that was requested?

2023-11-27 12:23 UTC, aince42 approved these changes

2023-11-27 12:36 UTC, Vin-RM approved these changes

2023-11-27 12:38 UTC, merged