Feature/implement propose and create decidable renderers
nmshd/cns-app pull request #108
Opened 2023-11-27 06:58 UTC by aince42

2023-11-27 12:42 UTC, Vin-RM approved these changes

2023-11-27 13:08 UTC, nicole-eb requested changes

2023-11-27 13:08 UTC, nicole-eb commented on packages/renderers/example/lib/pages/decidable_examples/decidable_create_request_item_example.dart
> +        children: [
This Column can be removed

2023-11-27 13:08 UTC, nicole-eb commented on packages/renderers/example/lib/pages/decidable_examples/decidable_propose_request_relationship_item_example.dart
> +        children: [
This Column can be removed

2023-11-27 13:08 UTC, nicole-eb commented on packages/renderers/example/lib/pages/decidable_examples/decidable_create_request_relationship_item_example.dart
> +        children: [
This Column can be removed

2023-11-27 13:08 UTC, nicole-eb commented on packages/renderers/example/lib/pages/decidable_examples/decidable_propose_request_item_example.dart
> +        children: [
This Column can be removed

2023-11-29 08:30 UTC, jkoenig134 approved these changes

2023-11-29 08:30 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/decidable_create_attribute_request_item.dart
> +  final VoidCallback? onEdit;
I am not ok with the type. But it's ok when it changes in @Vin-RM's canAccept PR.

2023-11-29 08:40 UTC, aince42 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/decidable_create_attribute_request_item.dart
> +  final VoidCallback? onEdit;
I'll check with Vinicius

2023-11-29 08:54 UTC, aince42 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/decidable_create_attribute_request_item.dart
> +  final VoidCallback? onEdit;
Yes it will changed on Vinicius's pr

2023-11-29 09:14 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/decidable_create_attribute_request_item.dart
> +  final VoidCallback? onEdit;
ok, you can merge

2023-11-29 09:28 UTC, merged