Fix/request renderer behaviour
nmshd/cns-app pull request #120
Opened 2024-01-10 11:40 UTC by Vin-RM

Fix DecidableReadAttributeRequest's behaviour.

2024-01-15 14:42 UTC, nicole-eb approved these changes

2024-01-15 15:11 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/widgets/value_renderer_list_tile.dart
> +            Checkbox(value: widget.checkboxSettings!.isChecked, onChanged: widget.checkboxSettings!.onUpdateCheckbox),
missing trailing comma

2024-01-15 15:12 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/widgets/value_renderer_list_tile.dart
>    @override
you forgot to dispose the controller

2024-01-15 15:15 UTC, jkoenig134 requested changes

2024-01-15 15:15 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/widgets/value_renderer_list_tile.dart
> +  dynamic inputValue;
remove

2024-01-15 15:15 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/widgets/value_renderer_list_tile.dart
> +      setState(() => inputValue = controller.value);
remove

2024-01-15 15:15 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/widgets/value_renderer_list_tile.dart
> +        inputValue: inputValue,
```suggestion
        inputValue: controller.value,
```

2024-01-15 15:15 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/decidable_read_attribute_request_item_renderer.dart
> +  void onUpdateInput({String? valueType, dynamic inputValue, required bool isComplex}) {
don't we need this new logic for propose?

2024-01-15 15:59 UTC, Vin-RM commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/decidable_read_attribute_request_item_renderer.dart
> +  void onUpdateInput({String? valueType, dynamic inputValue, required bool isComplex}) {
not applicable

2024-01-22 09:55 UTC, jkoenig134 approved these changes

2024-01-22 09:58 UTC, jkoenig134 submitted a review, later dismissed

2024-01-22 11:01 UTC, jkoenig134 approved these changes

2024-01-22 11:02 UTC, merged