Fix/improve renderer validations
nmshd/cns-app pull request #127
Opened 2024-01-29 14:12 UTC by Vin-RM

Improve existing validations and add remaining.
Improve checkbox logic

2024-01-29 15:20 UTC, nicole-eb requested changes

2024-01-29 15:20 UTC, nicole-eb commented on packages/value_renderer/lib/src/widgets/inputs/text_input.dart
> +    } else if (!input.isEmpty && !validateEquality(input)) {
``
```suggestion
    } else if (input.isNotEmpty && !validateEquality(input)) {
```

2024-01-29 15:20 UTC, nicole-eb commented on packages/value_renderer/lib/src/widgets/inputs/text_input.dart
> +    } else if (!input.isEmpty && !validateFormat(input)) {
```suggestion
    } else if (input.isNotEmpty && !validateFormat(input)) {
```

2024-01-29 15:20 UTC, nicole-eb commented on packages/value_renderer/lib/src/widgets/inputs/number_input.dart
> +      } else if (!input.isEmpty && !validateMinValue(numInput)) {
```suggestion
      } else if (input.isNotEmpty && !validateMinValue(numInput)) {
```

2024-01-29 15:20 UTC, nicole-eb commented on packages/value_renderer/lib/src/widgets/inputs/number_input.dart
> +      } else if (!input.isEmpty && !validateFormat(input)) {
```suggestion
      } else if (input.isNotEmpty && !validateFormat(input)) {
```

2024-01-29 15:20 UTC, nicole-eb commented on packages/value_renderer/lib/src/widgets/inputs/number_input.dart
> +      } else if (!input.isEmpty && !validateEquality(numInput)) {
```suggestion
      } else if (input.isNotEmpty && !validateEquality(numInput)) {
```

2024-01-30 13:45 UTC, nicole-eb approved these changes

2024-01-30 15:54 UTC, jkoenig134 requested changes
Only one small point. the rest LGTM

2024-01-30 15:54 UTC, jkoenig134 commented on packages/renderers/lib/src/request/request_item_renderer/decidable/decidable_read_attribute_request_item_renderer.dart
> +  }
I don't like the naming of this method. when I see the name I don't get why and when it is updated. When I look what the method does I see that it only gets checked - so no update just enabling.

Additionally this method should not be public.

2024-01-31 08:19 UTC, jkoenig134 approved these changes

2024-01-31 08:20 UTC, merged