runtime bridge integration tests in pipeline
nmshd/cns-app pull request #31
Opened 2023-05-10 08:24 UTC by Siolto

Executes the integration tests for the runtime bridge in the pipeline for iOS and android.

Current Runtimes:
- iOS (~9 minutes)
- android (~25minutes 🥲 )

2023-05-10 15:24 UTC, Siolto commented
Could decrease the android runtime to ~13 Minutes

2023-05-11 09:21 UTC, jkoenig134 requested changes

2023-05-11 09:21 UTC, jkoenig134 commented on .github/workflows/runtime_bridge_integration_tests.yml
> +        run: "xcrun xctrace list devices"
Ist das noch vom testen?

2023-05-11 09:21 UTC, jkoenig134 commented on .github/workflows/runtime_bridge_integration_tests.yml
> +      matrix:
Brauchen wir die Matrix tests?

2023-05-11 09:21 UTC, jkoenig134 commented on .github/workflows/runtime_bridge_integration_tests.yml
> +          - "iPhone 14 Simulator (16.2)" # the name of the simulator could be different depending on the macos version you are using
muss der Name genau passen, oder können wir da auch weniger spezifisch sein? vllt nur `iPhone` das sollte doch immer verfügbar sein

2023-05-11 09:21 UTC, jkoenig134 commented on .github/workflows/runtime_bridge_integration_tests.yml
> +      matrix:
auch hier, matrix sinnvoll?

2023-05-11 09:24 UTC, Siolto commented on .github/workflows/runtime_bridge_integration_tests.yml
> +        run: "xcrun xctrace list devices"
Ja das ist vorm testen, theoretisch kann der Befehl raus. Ist aber nett zu wissen was auf der VM für Simulatoren zu verfügung stehen

2023-05-11 09:26 UTC, Siolto commented on .github/workflows/runtime_bridge_integration_tests.yml
> +          - "iPhone 14 Simulator (16.2)" # the name of the simulator could be different depending on the macos version you are using
Nur iPhone reicht theoretisch dann wird halt der erste Treffer der zur Verfügung stehenden Simulatoren genommen. Das kann dann halt alles mögliche sein. Weil wir `macOS-latest` nehmen kann das von Zeit zu Zeit dann auch plötzlich wechseln

2023-05-11 09:26 UTC, Siolto commented on .github/workflows/runtime_bridge_integration_tests.yml
> +      matrix:
Theoretisch nicht, ist halt nice to have

2023-05-11 09:27 UTC, Siolto commented on .github/workflows/runtime_bridge_integration_tests.yml
> +      matrix:
Brauchen wir nicht zwingend

2023-05-11 09:27 UTC, jkoenig134 commented on .github/workflows/runtime_bridge_integration_tests.yml
> +          - "iPhone 14 Simulator (16.2)" # the name of the simulator could be different depending on the macos version you are using
Naja, so wie es hier ist wird die Pipeline irgendwann einfach krachen.

2023-05-11 09:28 UTC, jkoenig134 commented on .github/workflows/runtime_bridge_integration_tests.yml
> +      matrix:
können es auch lassen, dann ist es einfachere weitere devices hinzuzufügen. Weiß nur nicht wie relistisch es ist, wir hatten ja gesagt wir brauchen Android + ios und was für devices es sind ist uns egal.

2023-05-11 09:30 UTC, Siolto commented on .github/workflows/runtime_bridge_integration_tests.yml
> +          - "iPhone 14 Simulator (16.2)" # the name of the simulator could be different depending on the macos version you are using
Warum wird sie plötzlich krachen?

2023-05-11 09:31 UTC, jkoenig134 commented on .github/workflows/runtime_bridge_integration_tests.yml
> +          - "iPhone 14 Simulator (16.2)" # the name of the simulator could be different depending on the macos version you are using
wenn `iPhone 14 Simulator (16.2)` nicht mehr verfügbar ist? Oder hab ich das falsch verstanden?

2023-05-12 07:53 UTC, jkoenig134 approved these changes

2023-05-12 08:27 UTC, merged