Feature/add value renderer
nmshd/cns-app pull request #68
Opened 2023-07-31 08:55 UTC by Vin-RM

Value Renderer with two example pages:

- Input Examples, to show examples of each case
- Renderer, to show the rendering of a mock json similar to a real use case

2023-07-31 16:16 UTC, nicole-eb requested changes

2023-08-01 08:15 UTC, Vin-RM commented on packages/value_renderer/example/lib/main.dart
> +            // splashFactory: NoSplash.splashFactory,
In this case, a default return is needed. Removing this line will cause an error.

2023-08-01 08:17 UTC, nicole-eb commented on packages/value_renderer/example/lib/main.dart
> +            // splashFactory: NoSplash.splashFactory,
i was referring to the commented out code `// splashFactory: NoSplash.splashFactory,`

2023-08-02 07:26 UTC, jkoenig134 requested changes

2023-08-02 07:26 UTC, jkoenig134 commented on packages/value_renderer/example/analysis_options.yaml
> +include: package:flutter_lints/flutter.yaml
should include the root folder `analysis_options.yaml`

2023-08-02 07:26 UTC, jkoenig134 commented on packages/value_renderer/example/lib/pages/renderer.dart
> +                        ));
missing comma for formatting
```suggestion
                        ),);
```

2023-08-02 07:26 UTC, jkoenig134 commented on packages/value_renderer/example/lib/main.dart
> +Future<Map<String, dynamic>> loadDecidableJson() async {
You should return a RequestDVO instead and run RequestDVO#fromJson on the JSON payload.

This will change much coding, I'll go on with the review when this is done.

2023-08-02 07:26 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/utils/parse_render_hint.dart
> +}
all this can be `EnumName.values.byName(string)`

2023-08-11 07:59 UTC, jkoenig134 requested changes

2023-08-11 07:59 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/inputs/datepicker_button.dart
> +    final lastDate = DateTime(2200, now.month, now.day);
IMO the DatePicker should allow all dates, it can be made stricter later for example for the BirthDate

2023-08-11 07:59 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/inputs/dropdown_select_button.dart
> +        ),
overuse of `dynamic` - can be much stricter

2023-08-11 07:59 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/inputs/switch_button.dart
> +  late bool light;
I'd suggest `enabled` or `value`

2023-08-11 07:59 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/inputs/text_input.dart
> +      controller: TextEditingController()..text = widget.initialValue!,
floating controller

2023-08-17 13:11 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/renderers/string.dart
> +      {super.key, required this.fieldName, this.values, this.editType, this.dataType, required this.initialValue, required this.valueHints});
missing trailing comma

2023-08-24 06:25 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/renderers/string.dart
> +    // Replacing "StepInput"
can you tell more about why there is a comment?

Maybe give examples that would result in a StepInput

2023-08-24 08:42 UTC, Vin-RM commented on packages/value_renderer/lib/src/widgets/renderers/string.dart
> +    // Replacing "StepInput"
This comment is to indicate that instead of using the actual component  [("Step Input")](https://sapui5.hana.ondemand.com/#/entity/sap.ui.webc.main.StepInput/sample/sap.ui.webc.main.sample.StepInput), we are currently replacing it with a regular Number input, like we talked about in a daily.

2023-08-24 08:54 UTC, jkoenig134 requested changes

2023-08-24 08:54 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/renderers/string.dart
> +    // Replacing "StepInput"
i know that, but not everyone reading that is. Please be more precise in that comment.

2023-08-24 08:54 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/inputs/dropdown_select_input.dart
> +        ), // Label
```suggestion
        ),
```

2023-08-24 08:55 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/inputs/number_input.dart
> +      decoration: InputDecoration(labelText: widget.fieldName),
untranslated fieldname, please re-check all of them.

2023-08-24 09:11 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/inputs/text_input.dart
> +    final translatedText = FlutterI18n.translate(context, widget.fieldName);
only if it starts with i18n://

2023-08-24 09:11 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/inputs/number_input.dart
> +    final translatedText = FlutterI18n.translate(context, widget.fieldName);
see other comment

2023-08-24 09:39 UTC, nicole-eb submitted a review, later dismissed

2023-08-24 09:39 UTC, nicole-eb commented on packages/value_renderer/example/lib/main.dart
> +                ],
```suggestion
                for (final item in _menu)
                  _DrawerButton(
                    icon: item.icon,
                    title: item.title,
                    isSelected: item == _selectedMenuItem,
                    onPressed: () {
                      setState(() {
                        _selectedMenuItem = item;
                      });

                      if (mounted) Navigator.of(context).pop();
                    },
                  ),
```

2023-08-24 09:39 UTC, nicole-eb commented on packages/value_renderer/example/lib/main.dart
> +    },
```suggestion
    pageBuilder: (context) => const InputExamples()
```

2023-08-24 09:39 UTC, nicole-eb commented on packages/value_renderer/example/lib/main.dart
> +    },
```suggestion
    pageBuilder: (context) => const Renderer()
```

2023-08-24 09:39 UTC, nicole-eb commented on packages/value_renderer/example/lib/main.dart
> +              return Colors.transparent;
```suggestion
              if (isSelected) return const Color(0xFFBBBB);
              if (states.contains(MaterialState.hovered)) return Colors.grey.withOpacity(0.1);
              return Colors.transparent;
```

2023-08-24 09:39 UTC, nicole-eb commented on packages/value_renderer/example/lib/main.dart
> +            ),
```suggestion
            Expanded(child: Text(title)),
```
**This is a generall example**. You can leave the trailing comma out if it so the widget can be in one row if its not to long.

2023-08-24 11:18 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/inputs/dropdown_select_input.dart
> +          onChanged: (dynamic newValue) {
dynamic

2023-08-28 09:40 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/inputs/datepicker_input.dart
> +      final AttributeValue value => logCannotHandle(value),
it's currently the only date.

2023-08-28 09:43 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/inputs/slider_input.dart
> +    }
you throw when it's null, why don't you just make it required above?!

2023-08-28 09:48 UTC, jkoenig134 submitted a review, later dismissed

2023-08-28 10:48 UTC, jkoenig134 requested changes

2023-08-28 10:48 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/renderers/number.dart
> +      if (min == null || max == null) throw Exception('trying to render without a min/max value');
trying to render what?

2023-08-28 12:17 UTC, jkoenig134 approved these changes

2023-08-29 07:21 UTC, merged