Test/identity attribute values tests
nmshd/cns-app pull request #8
Opened 2023-03-27 13:30 UTC by aince42

2023-03-27 13:56 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/example/lib/views/incoming_requests_facade_view.dart
>  import 'package:enmeshed_types/enmeshed_types.dart';
`import 'package:enmeshed_types/enmeshed_types.dart' as enmeshedTypes;`, State verstecken kann irgendwie nicht die Lösung sein. Genau das gleiche Überall wo du State versteckt hast aus den enmeshed_types.

2023-03-29 08:22 UTC, Siolto requested changes
just minor refactoring in my opinion required. Rest looks good 👍

2023-03-29 08:22 UTC, Siolto commented on packages/enmeshed_runtime_bridge/example/lib/main_demo.dart
> +    final messagesToDisplay = messages.where((e) => e.content is types.Mail).toList()..sort((a, b) => a.createdAt.compareTo(b.createdAt));
can we use a more meaningful variable than only `e`?

2023-03-29 08:28 UTC, Siolto approved these changes

2023-03-29 09:08 UTC, merged