Feature/input styles
nmshd/cns-app pull request #91
Opened 2023-10-16 12:53 UTC by Vin-RM

2023-10-16 13:24 UTC, jkoenig134 commented
Pipeline is failing, you shoud update at first the base branch to main then this branch to the base one.

Additionally - please first do some review rounds internally and then assign me.

2023-10-16 13:24 UTC, jkoenig134 commented
Also - why is this a draft? Typically drafts should not be given out for review.

2023-10-16 13:56 UTC, jkoenig134 commented
@Vin-RM https://github.com/nmshd/cns-app/pull/90 fixes the bug with the version that cannot be fetched. We have to merge this first.

2023-10-17 09:41 UTC, nicole-eb requested changes

2023-10-17 09:41 UTC, nicole-eb commented on packages/value_renderer/lib/src/widgets/renderers/complex.dart
>      final translatedText = fieldName.startsWith('i18n://') ? FlutterI18n.translate(context, fieldName.substring(7)) : fieldName;
same

2023-10-17 09:43 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/inputs/dropdown_select_input.dart
> +    final translatedText = fieldName.startsWith('i18n://') ? FlutterI18n.translate(context, fieldName.substring(7)) : fieldName;
I don't think so, fieldName is also used in the `FlutterI18n.translate` call which make the whole line more readable.

2023-10-17 09:46 UTC, nicole-eb approved these changes

2023-10-17 11:15 UTC, jkoenig134 commented on packages/value_renderer/lib/src/widgets/inputs/segmented_button_input.dart
> +            final translatedText = fieldName.startsWith('i18n://') ? FlutterI18n.translate(context, fieldName.substring(7)) : fieldName;
you are using the context only once, so IMO it should not be put in an extra variable.

2023-10-17 11:18 UTC, jkoenig134 approved these changes

2023-10-17 12:32 UTC, merged