Feature/update request items
nmshd/cns-app pull request #92
Opened 2023-10-17 10:13 UTC by nicole-eb

2023-10-17 10:51 UTC, Vin-RM commented on packages/renderers/lib/src/renderers/request_item_renderer/widgets/identity_attribute_renderer.dart
> +      titles: const ['Rolle', 'Organization', 'Unit'],
Typo: should this be 'Role"?

2023-10-17 12:46 UTC, aince42 approved these changes

2023-10-17 13:31 UTC, Vin-RM approved these changes

2023-10-19 06:13 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/consent_request_item_renderer.dart
> +      title: '',
empty title?

2023-10-19 06:18 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/consent_request_item_renderer.dart
> +          if (item.link != null) Text(item.link!),
I think we discussed on how the consent should look.

And I think we should use a trailing IconButton that opens the link (you can use https://fonts.google.com/icons?selected=Material+Symbols+Outlined:open_in_new:FILL@0;wght@400;GRAD@0;opsz@24&icon.platform=web as the icon)

2023-10-19 08:35 UTC, jkoenig134 requested changes

2023-10-23 12:46 UTC, nicole-eb commented on packages/renderers/lib/src/renderers/widgets/custom_list_tile.dart
>  class CustomListTile extends StatelessWidget {
should i still change the naming or is Alis version okay ?

2023-10-23 14:22 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/widgets/custom_list_tile.dart
>  class CustomListTile extends StatelessWidget {
I think a rename would be better.

2023-10-23 14:23 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/authentication_request_item_renderer.dart
> +        const Divider(height: 0),
why do we need this divider?

2023-10-23 14:23 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/authentication_request_item_renderer.dart
> +        const Divider(height: 0),
if you remove it please also remove the column

2023-10-23 14:24 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/consent_request_item_renderer.dart
> +                  log(e.toString());
we have out logger for this

2023-10-23 14:25 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/decidable_register_attribute_listener_request_item_renderer.dart
> +        const Divider(height: 0),
same as in the other widget, why do we need this divider in this renderer?

2023-10-23 14:25 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/free_text_request_item_renderer.dart
> +        const Divider(height: 0),
see above

2023-10-23 14:25 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/propose_attribute_request_item_renderer.dart
> +        const Divider(height: 0),
see above

2023-10-23 14:26 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/read_attribute_request_item_renderer.dart
> +        const Divider(height: 0),
see above

2023-10-23 14:26 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/register_attribute_listener_request_item_renderer.dart
> +        const Divider(height: 0),
see above

2023-10-23 14:27 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/widgets/custom_list_tile.dart
>                      const SizedBox(height: 2),
the sized box should also be removed if value is null

2023-10-23 14:28 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/widgets/complex_attribute_list_tile.dart
> -            SizedBox(width: 96, child: trailing ?? IconButton(onPressed: onPressed, icon: const Icon(Icons.info))),
trailing is optional, you should only show the sized box if trailing is defined.

2023-10-23 14:29 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/widgets/identity_attribute_renderer.dart
can we share code with `DraftRelationshipAttributeRenderer` and maybe other renderers? I think I saw this multiple times.

2023-10-24 08:14 UTC, nicole-eb commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/decidable_authentication_request_item_renderer.dart
> +    return CustomListTile(title: '', description: item.name);
i am not working on decidables in this task

2023-10-24 08:14 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/widgets/identity_attribute_renderer.dart
the whole build method seems to be copy paste, thats what I thought can be code-shared.

2023-10-24 08:15 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/decidable_authentication_request_item_renderer.dart
> +    return CustomListTile(title: '', description: item.name);
@aince42 told me it will be fixed in your PR, so please keep it on track.

2023-10-24 08:16 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/decidable_authentication_request_item_renderer.dart
> +    return CustomListTile(title: '', description: item.name);
(it doesn't have to be fixed in this PR, it just has to be tackeled before I review the big PR)

2023-10-24 13:05 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/create_attribute_request_item.dart
> +    };
why do you need the switch, when you do the same in all cases?

2023-10-24 13:05 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/decidable_share_attribute_request_item_renderer.dart
>          },
why do you need the switch, when you do the same in all cases?

2023-10-24 13:13 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/decidable_share_attribute_request_item_renderer.dart
>          const SizedBox(height: 30),
not part of your pr, but what is this sized box?

2023-10-24 13:29 UTC, nicole-eb commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/decidable_share_attribute_request_item_renderer.dart
>          const SizedBox(height: 30),
i think it was a leftover from spacing something. will be removed in the decidable share task

2023-10-24 13:30 UTC, jkoenig134 approved these changes

2023-10-24 14:19 UTC, merged