Feature/add decidable identity attribute value renderer
nmshd/cns-app pull request #93
Opened 2023-10-17 12:20 UTC by aince42

2023-10-17 13:06 UTC, Vin-RM requested changes

2023-10-17 13:06 UTC, Vin-RM commented on packages/renderers/example/lib/pages/home_screen.dart
> +      _MenuGroup(title: 'Dedicdable Read Attriubute', items: [
Typo:
```suggestion
      _MenuGroup(title: 'Decidable Read Attribute', items: [
```

2023-10-17 13:31 UTC, Vin-RM approved these changes

2023-10-17 14:31 UTC, jkoenig134 requested changes
subtitle is a real english word. please use `subtitle` instead of `subTitle` everywhere.

2023-10-17 14:31 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/decidable/widgets/identity_attribute_value_renderer.dart
> +        'i18n://attributes.values.Affiliation.unit.label',
this counts for every i18n string in the file

2023-10-17 14:39 UTC, aince42 commented on packages/renderers/lib/src/renderers/widgets/complex_attribute_list_tile.dart
> +                      ),
I tried it, but unfortunately it is not possible.
We could translate the text outside of the widget, but I think this is the better way.

2023-10-17 14:49 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/widgets/complex_attribute_list_tile.dart
> +                      ),
nope, translate outside is totally fine!

2023-10-17 14:50 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/widgets/complex_attribute_list_tile.dart
> +    }
this messes up the order of subtitles and titles, I really don't get what you are doing here.

2023-10-19 07:38 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/widgets/custom_list_tile.dart
look at nicoles PR for naming. you should talk about that or you will have clashes when merging.

2023-10-20 07:41 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/widgets/query_renderer.dart
> +    return CustomListTile(title: '', value: query.name);
I am confused if this empty titles in this file.

2023-10-20 07:41 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/request_item_renderer/widgets/relationship_attribute_renderer.dart
> +    return CustomListTile(title: '', value: value.consent);
empty titles in this file

2023-10-20 07:41 UTC, jkoenig134 commented on packages/renderers/lib/src/renderers/widgets/custom_list_tile.dart
> +                    TranslatedText(value, style: const TextStyle(fontSize: 16)),
why translating the value?

2023-10-20 10:47 UTC, jkoenig134 approved these changes
I Approve that this can finally be merged - but please look at the not-outdated comments and resolve them in @nicole-eb's PR before you assign me for review there.

Also my comment about subTitle -> subtitle is still open, please resolve this (if you don't remove that).

2023-10-20 12:16 UTC, merged